### PR TITLE
Delete field Address

### LINKED ISSUE #96: Fix wrong prefix for Emergency Contact in AddCommandParser
Fix in AddCommandParser by changing prefix of Emergency Contact to the correct "/ec" from "/a"

### PR DESCRIPTION
**Pull request by phfabs**
Fixes #96

### CODE REVIEW

File: src/test/java/seedu/address/logic/parser/AddCommandParserTest.java [hunk 1]
```diff
@@ -159,7 +159,7 @@ public void parse_repeatedNonTagValue_failure() {
 
         // invalid address
         assertParseFailure(parser, validExpectedPersonString + INVALID_EMERGENCY_CONTACT_DESC,
-                Messages.getErrorMessageForDuplicatePrefixes(PREFIX_ADDRESS));
+                Messages.getErrorMessageForDuplicatePrefixes(PREFIX_EMERGENCY_CONTACT));
```
Comment (memoflora) [inline src/test/java/seedu/address/logic/parser/AddCommandParserTest.java]: Great, you changed the error message to the new prefix.
